Added abort hooks to the init stages

diff --git a/host/init/stage-one b/host/init/stage-one
--- a/host/init/stage-one
+++ b/host/init/stage-one
@@ -6,6 +6,12 @@ set -e
 # second stage initialization.  This stage should NOT perform anything complicated
 # such as docker operations.
 
+# Abort stage one if environment is set
+if [ "${ABORT_PARASITE_INIT_STAGE_ONE}" = "true" ]; then
+  echo >&2 "Aborting parasite stage one initialization per ABORT_PARASITE_INIT_STAGE_ONE environment variable"
+  exit 1
+fi
+
 # Make sure we are running at root
 if ! [ "$(whoami)" = "root" ]; then
   echo >&2 "Parasite stage one initialization must be run as root!"
diff --git a/host/init/stage-two b/host/init/stage-two
--- a/host/init/stage-two
+++ b/host/init/stage-two
@@ -8,6 +8,12 @@ set -e
 # order serially.  Note however that cloud-config yml initializers are spawned
 # in parallel and cannot be guaranteed to run in order.
 
+# Abort stage two if environment is set
+if [ "${ABORT_PARASITE_INIT_STAGE_TWO}" = "true" ]; then
+  echo >&2 "Aborting parasite stage two initialization per ABORT_PARASITE_INIT_STAGE_TWO environment variable"
+  exit 1
+fi
+
 # Pre-pull all docker images at the start to ensure a smoother initialization
 echo "Pre-pulling all required docker images"
 systemctl start docker-check-image-update.service
